language: node_js
 node_js:
 - "stable"
 install:
  - yarn --frozen-lockfile
 cache:
 directories:
   - node_modules
 script:
 - yarn test -- --coverage
 - yarn build

 after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls